version: '2.3'
services:
  worker:
    image: myoung34/github-runner:latest
    environment:
       ACCESS_TOKEN: :)
       RUNNER_SCOPE: org
       ORG_NAME: kinsend
       LABELS: ks-linux
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within
