name: terraform-plan

on:
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ks-linux

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: fetch master branch
        run: git fetch origin master

      - name: detect changed module path
        id: detect
        run: ./scripts/actions-detect-modules

    outputs:
      module_path_matrix: ${{ steps.detect.outputs.module_path_matrix }}
      status: ${{ steps.detect.outputs.status }}

  plan:
    runs-on: ks-linux
    needs: setup
    if: ${{ needs.setup.outputs.status == 'ok' }}
    strategy:
      matrix: ${{fromJSON(needs.setup.outputs.module_path_matrix)}}
    defaults:
      run:
        working-directory: ${{ matrix.module_path }}
    env:
      TF_CLI_ARGS: '-no-color'
      TF_VAR_aws_profile: kinsend-infra
      TF_LOG: error

    # This permission is required to allow writing comments and reporting check status.
    permissions:
      actions: read
      checks: write
      contents: read
      issues: write
      pull-requests: write
      repository-projects: read
      statuses: write

    steps:

      - uses: actions/checkout@v3

      # this setup simply allows us to invoke scripts in the ./scripts directory
      # directly, without specifying a path
      - name: update $PATH
        run: echo "${GITHUB_WORKSPACE}/scripts" >> "${GITHUB_PATH}"

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: setup SSH configuration
        run: actions-setup-ssh-config
        env:
          SSH_KEY: ${{ secrets.KS_DEVOPS_BOT_SSH_KEY }}

      - name: setup AWS configuration
        run: actions-setup-aws-config

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: init
        id: init
        run: terraform init

      - name: validate
        id: validate
        run: terraform validate

      - name: plan
        id: plan
        run: terraform plan -out tfplan.binary

      - name: Terraform show
        run: terraform show -json tfplan.binary > plan.json

      - name: post results
        if: always()
        uses: actions/github-script@v6
        continue-on-error: true
        env:
          STEP_INIT_OUTCOME: ${{ steps.init.outcome }}
          STEP_INIT_STDERR: ${{ steps.init.outputs.stderr }}
          STEP_INIT_STDOUT: ${{ steps.init.outputs.stdout }}
          STEP_VALIDATE_OUTCOME: ${{ steps.validate.outcome }}
          STEP_VALIDATE_STDERR: ${{ steps.validate.outputs.stderr }}
          STEP_VALIDATE_STDOUT: ${{ steps.validate.outputs.stdout }}
          STEP_PLAN_OUTCOME: ${{ steps.plan.outcome }}
          STEP_PLAN_STDERR: ${{ steps.plan.outputs.stderr }}
          STEP_PLAN_STDOUT: ${{ steps.plan.outputs.stdout }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const helpers = require('./scripts/actions-script-helpers.js');
        
            helpers.commentResults(
              github,
              context,
              context.issue.number,
              '${{ matrix.module_path }}',
              [
                {name: "init"},
                {name: "validate"},
                {name: "plan", detailedSuccess: true},
              ],
            );
